### ISSUE TITLE
Archiefnominatie.bewaren moet worden blijvend_bewaren

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/VNG-referentielijsten#1]
Dit komt overeen met RGBZ en dekt beter de lading.

**Comment by annashamray** [comment]
local constant `ArchiefNominaties` is replaced with `zds_schema.constants.Archiefnominatie` which has two choices: "blijvend_bewaren" and "vernietigen"

**Comment by sergei-maertens** [comment]
Yep, should be fixed via https://github.com/VNG-Realisatie/VNG-referentielijsten/commit/2b8e1e6a647404b647c59735b03d952e3900fd7c

One consideration is that the selectielijst has three options, while ZTC and ZRC only have two, so there's a mapping happening there (or should be happening), but this covers most of the use cases already.
