### ISSUE TITLE
Implementatie Referentielijsten door VNG

### ISSUE THREAD

**Issue by ghost** [VNG-Realisatie/VNG-referentielijsten#27]
Volgens de README van dit project en de specificaties van de ZGW API wordt deze API centraal beheerd, zodat iedereen dezelfde referentielijsten gebruikt. Echter kunnen we nergens een werkende complete versie hiervan vinden. 

Is het de bedoeling dat iedere leverancier van een ZGW API zelf de Referentielijsten API implementeert, of wordt deze inderdaad publiek door VNG geleverd. In geval van het laatste; Waar is deze te vinden en is deze volledig en productie gereed.

Alpha versie bevat geen volledig inhoud:
https://referentielijsten-api.vng.cloud/api/v1/schema/ 
https://referentielijsten-api.vng.cloud/api/v1/resultaattypeomschrijvingen

En andere genoemde link doet het uberhaupt niet:
https://ref.tst.vng.cloud/referentielijsten/

**Comment by sergei-maertens** [comment]
https://selectielijst.openzaak.nl/api/v1/schema/ is wel in gebruik en onderhouden, maar die is NIET door VNG beheerd.

Het Open Zaak team importeert nieuwe selectielijsten in deze omgeving als deze beschikbaar komen.

De bal ligt in het kamp van VNG om dit daadwerkelijk in beheer te nemen - vooral omdat zijn bronhouder zijn van deze gegevens. Tot nu toe hebben we hier geen positief antwoord op ontvangen.

**Comment by joeribekker** [comment]
Ik ben zo blij dat iemand hier eindelijk over valt!

@michielverhoef Helaas weet ik het antwoord van VNG al, maar toch laat ik het aan u.
