### ISSUE TITLE
Website link van dit github project werkt niet

### ISSUE THREAD

**Issue by mcbeelen** [VNG-Realisatie/VNG-referentielijsten#44]
Bij dit project staat een link naar een website vermeld, welke verwijst naar: 
[referentielijsten-api.vng.cloud/](https://referentielijsten-api.vng.cloud/)

Het openen van die pagina geeft een `404 page not found`

**Comment by melsk-r** [comment]
Ik heb de link verwijderd aangezien er geen GitHub Pages omgeving meer is voor deze repository. Of dat terecht is weet ik niet, @michielverhoef weet jij dat?

**Comment by michielverhoef** [comment]
Dat kan goed kloppen, de Referentielijsten API  is opnieuw gebouwd. De insteek is dat het een zuivere API is, zonder beheerschermen etc.  [referentielijsten-api.vng.cloud/](https://referentielijsten-api.vng.cloud/) is trouwens geen githubpages omgeving maar een soort startpagina voor elke referentieimplementatie.  Dit werkt alleen voor de referentieimplementaties die op basis van Django gebouwd zijn, zoals Zaken, Documenten, Catalogi, Besluiten etc. De Referentielijsten API is gemaakt in golang.

Overigens is de OAS wel te raadplegen via https://referentielijsten-api.vng.cloud/api/v1/schema

**Comment by melsk-r** [comment]
Ok, het lijkt me dat dit issue dan gesloten kan worden.
